plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}"
    id "maven-publish"
}

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

repositories {
    maven {
        name = "Mod Menu"
        url = "https://maven.terraformersmc.com/releases/"
    }
    maven {
        name = "DevLogin"
        url = "https://maven.covers1624.net/"
    }
    maven {
        name = "Resourceful Config"
        url = "https://maven.teamresourceful.com/repository/maven-public/"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    // Mod Menu
    implementation("com.terraformersmc:modmenu:${project.modmenu_version}")
    // Resourceful Config
    implementation "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-${project.rconfig_version}"

    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.8.0"
    include "org.jetbrains.kotlin:kotlin-stdlib:1.8.0"

    implementation "com.fasterxml.jackson.core:jackson-databind:2.17.0"
    include "com.fasterxml.jackson.core:jackson-databind:2.17.0"
    include "com.fasterxml.jackson.core:jackson-core:2.17.0"
    include "com.fasterxml.jackson.core:jackson-annotations:2.17.0"

    implementation "io.socket:socket.io-client:2.1.1"
    include "io.socket:socket.io-client:2.1.1"
    include "io.socket:engine.io-client:2.1.0"
    include "com.squareup.okhttp3:okhttp:3.12.12"
    include "org.json:json:20231013"
    include "com.squareup.okio:okio:3.4.0"

    // Dev Login
    localRuntime "net.covers1624:DevLogin:0.1.0.5"
}

loom {
    accessWidenerPath = file("src/main/resources/mineboxadditions.accesswidener")
    runs {
        clientLogin {
            client()
            ideConfigGenerated true
            programArgs "--launch_target", "net.fabricmc.loader.impl.launch.knot.KnotClient"
            mainClass.set "net.covers1624.devlogin.DevLogin"
        }
    }
}

base {
    archivesName = project.archives_base_name
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version,
                "minecraft_version": inputs.properties.minecraft_version,
                "loader_version": inputs.properties.loader_version
    }
}

java {
    withSourcesJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

jar {
    from("LICENSE") {
        rename { "${it}_${base.archivesName.get()}" }
    }
}
