org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
mod_version=1.15.1
maven_group=io.dampen59.mineboxadditions
archives_base_name=mineboxadditions

# Fabric Properties (https://fabricmc.net/develop)
minecraft_version=26.1
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_api_version=0.145.1+26.1

# Mod Menu (https://modrinth.com/mod/modmenu/versions?l=fabric)
modmenu_version=18.0.0-beta.1
# Resourceful Config (https://modrinth.com/mod/resourceful-config/versions)
rconfig_version=26.1:4.0.1
